---
title: "Predict RFO"
author: "João Vitor F Cavalcante"
date: "26/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read-data, message=FALSE}
library(readxl)
library(dplyr)
library(caret)
library(neuralnet)

dataset <- read_excel("data/Data_v1.xlsx")[-1,] %>% 
  mutate(RFO = as.double(RFO),
         TEM = as.double(TEM),
         # Replace NA with median on PERM
         PERM = ifelse(is.na(PERM), median(PERM, na.rm = TRUE), PERM))
```

### Partitioning dataset

```{r data-slice}
set.seed(1024)

partitioned <- createDataPartition(y = dataset$RFO, p = 0.7, list = FALSE)

training <- dataset[partitioned, -1]
testing <- dataset[-partitioned, -1]

```

## Linear Regression

### Build model

```{r}
set.seed(4080)

lm_mod <- lm(RFO ~ ., data = training)

knitr::kable(broom::glance(lm_mod),
             format = "html",
             table.attr = 'class="table table-striped table-sm"')
```

### Test model

```{r}
lm_predictions <- predict(lm_mod, testing)

actual_preds <- data.frame(cbind(actuals = testing$RFO, predicted = lm_predictions))

knitr::kable(actual_preds,
             format = "html",
             table.attr = 'class="table table-striped table-sm"')
```

### Results

```{r}
lm_rmse <- sqrt(mean((actual_preds$actuals - actual_preds$predicted) ^ 2))
lm_correlation <- cor(actual_preds)[1, 2] ^ 2
minmax_accuracy <- mean(apply(actual_preds, 1, min) / apply(actual_preds, 1, max))

res_summary <-
  tibble(
    RMSE = round(lm_rmse, digits = 3),
    R2 = round(lm_correlation, digits = 3),
    `MinMax Accuracy` = round(minmax_accuracy, digits = 3)
  )

knitr::kable(res_summary,
             format = "html",
             table.attr = 'class="table table-striped table-sm"')
```


## SVM with Radial Basis Function

### Build model

```{r train-svm}
set.seed(2021)

ctrl <- trainControl(
  method = "cv",
  number = 10,
)

tuneGrid <- expand.grid(
  C = c(0.22, 0.25, 0.4),
  sigma = 0.122
)

svm_model <- train(
  RFO ~ .,
  data = training,
  method = "svmRadial",
  preProcess = c("center", "scale"),
  trCtrl = ctrl,
  tuneGrid = tuneGrid
) 
```

### Test model

```{r test-svm}
svm_features <- testing %>% 
  select(-c(RFO))

svm_target <- testing %>% 
  pull(RFO)

svm_predictions <- predict(svm_model, newdata = svm_features)  
```

### SVM results

```{r svm-metrics-2}
svm_rmse <- sqrt(mean((svm_target - svm_predictions) ^ 2))

svm_cor <- cor(svm_target, svm_predictions) ^ 2

svm_metrics_df <- data.frame(RMSE = round(svm_rmse, digits = 3),
           R2 = round(svm_cor, digits = 3))

knitr::kable(svm_metrics_df, format = "html", table.attr = 'class="table table-striped table-sm"')
```

```{r svm-resulting metrics}

plot(svm_model)

```

## ANN

### Build model

```{r}
set.seed(2048)

maxs <- apply(dataset[, -1], 2, max)
mins <- apply(dataset[, -1], 2, min)

training_scaled <- as.data.frame(scale(training, center = mins,
                                      scale = maxs - mins))
testing_scaled <- as.data.frame(scale(testing, center = mins,
                                      scale = maxs - mins))
nn <- neuralnet(
  RFO ~ .,
  data = training_scaled,
  hidden = c(8, 5, 3),
  linear.output = TRUE
)
```

### Test model

```{r}
# Computing RMSE
pr_nn <- predict(nn, testing_scaled)

pr_nn_predicted <- pr_nn * (max(dataset$RFO) - min(dataset$RFO) + min(dataset$RFO))

nn_RMSE <- sqrt(mean((testing$RFO - pr_nn_predicted) ^ 2))
nn_cor <-  cor(testing$RFO, pr_nn_predicted) ^ 2
```

### Results

```{r}
nn_metrics <- tibble(
  RMSE = round(nn_RMSE, digits = 3),
  R2 = round(nn_cor, digits = 3)
)

knitr::kable(nn_metrics, format = "html", table.attr = 'class="table table-striped table-sm"')
```


```{r}
plot(testing$RFO, pr_nn_predicted, col = "red",
     main = 'Real vs Predicted', xlab = "Real", ylab = "Predicted")
abline(0, 1, lwd = 2)
```
